env:
  global:
    - LD_LIBRARY_PATH=$HOME/libhsl
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - NODE_TOTAL=2
  matrix:
    - NODE_INDEX=0
    - NODE_INDEX=1

sudo: required
dist: trusty
language: generic

before_script:
  - set -e
  - set -o pipefail  # otherwise, piping with grep discards exit statuses
  - git clone https://github.com/meco-group/bob.git
  - pushd bob && source setup.sh && popd
  - bob_get libhsl.tar.gz && mkdir $HOME/libhsl && tar -xf libhsl.tar.gz -C $HOME/libhsl

script:
  - python setup.py nosetests

# matrix:
#   include:
#     - env:
#         - NODE_INDEX=0
#     - script:
#         - python setup.py nosetests
#   include:
#     - env:
#         - NODE_INDEX=1
#     - script:
#         - python setup.py nosetests

# matrix:
#   include:
#     - script:
#         # - cd examples
#         - chmod 644 *.py
#         - "nosetests -s --verbosity=4 --tests=$(python .select_examples.py 3 1) --with-xcoverage --cover-package=omgtools --cover-tests 2> >(grep -v -P 'DEBUG: (?!wantFile)')"
#         # - python p2p_holonomic.py
#     - script:
#         - cd examples
#         - chmod 644 *.py
#         - python formation_quadrotor.py
#     - script:
#         - cd examples
#         - chmod 644 *.py
#         - python p2p_holonomic_export.py
#         - pushd export
#         - make && pushd bin
#         - ./Point2Point
#         - popd
#         - popd

# script:
#   - cd examples
#   - chmod 644 *.py # nose doesnt match executable files
#   - "nosetests -s --verbosity=4 -i '\\.py$' . --with-xcoverage --cover-package=omgtools --cover-tests 2> >(grep -v -P 'DEBUG: (?!wantFile)')"
#   - pushd export
#   - make && pushd bin
#   - ./Point2Point
#   - popd
#   - popd
#   - pushd export_f
#   - make && pushd bin
#   - ./FormationPoint2Point
#   - popd
#   - popd
#   - pushd export_r
#   - make && pushd bin
#   - ./RendezVous
#   - popd
#   - popd

after_success:
  - coveralls

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo pip install .

before_install:
  - sudo add-apt-repository main
  - sudo apt-get update
  - sudo apt-get install -y imagemagick python-tk python-pip python-dev
  - sudo apt-get install -y libatlas3-base libgfortran3 liblapack3 libslicot0 --install-recommends
  - sudo pip install nosexcover coveralls
  - sudo apt-get install -y valgrind xvfb
