env:
  global:
    - LD_LIBRARY_PATH=$HOME/libhsl
    # - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - COVERALLS_PARALLEL=1
    - NODE_TOTAL=4
  matrix:
    - NODE_INDEX=0
    - NODE_INDEX=1
    - NODE_INDEX=2
    - NODE_INDEX=3

sudo: required
dist: trusty
language: generic

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

before_script:
  - set -e
  - set -o pipefail  # otherwise, piping with grep discards exit statuses
  - git clone https://github.com/meco-group/bob.git
  - pushd bob && source setup.sh && popd
  - bob_get libhsl.tar.gz && mkdir $HOME/libhsl && tar -xf libhsl.tar.gz -C $HOME/libhsl

script:
  - nosetests --verbosity=2 --nocapture --with-xcoverage --cover-package=omgtools --cover-tests

after_success:
  - coveralls

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo pip install .

before_install:
  - sudo add-apt-repository main
  - sudo apt-get update
  - sudo apt-get install -y python-pip python-numpy python-scipy python-matplotlib
  - sudo apt-get install imagemagick
  - sudo pip install nosexcover coveralls
  - sudo pip install six
  - sudo apt-get install -y valgrind xvfb
